'use client';
import { useState } from 'react';
import { FrameCard } from './FrameCard';
import { useApi } from './useApi';
type Suggestion={id:string;topic:string;status:string;targetType:string;proposedPositionText:string;appliedUrl?:string;appliedAt?:string};
type Preview={targetTitle:string;targetUrl:string;text:string;digest:string};
export function ApplySuggestionsPanel(){
 const {data,error,refresh}=useApi<{proposals:Suggestion[]}>('/api/proposals?status=accepted',30000);
 const history=useApi<{proposals:Suggestion[]}>('/api/proposals?status=applied',30000);
 const [preview,setPreview]=useState<{id:string;data:Preview}|null>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 async function inspect(id:string){setBusy(true);setMessage('');try{const r=await fetch(`/api/proposals/${id}/apply`);const b=await r.json();if(!r.ok)throw Error(b.error);setPreview({id,data:b});}catch(e){setMessage(String(e));}finally{setBusy(false);}}
 async function apply(){if(!preview)return;setBusy(true);try{const r=await fetch(`/api/proposals/${preview.id}/apply`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({digest:preview.data.digest})});const b=await r.json();if(!r.ok)throw Error(b.error);setMessage('Applied to Notion. Future routines must load this updated source before it can affect a draft.');setPreview(null);refresh();history.refresh();}catch(e){setMessage(String(e));}finally{setBusy(false);}}
 return <FrameCard className="p-5"><h2 className="panel-heading">Apply approved improvements</h2><p className="mt-2 text-sm text-ink-dim">Preview the exact destination and wording. Applying appends an approved amendment to your Notion source; existing content stays intact.</p>{error&&<p role="alert">{error}</p>}{message&&<p role="status" className="mt-3 text-sm">{message}</p>}{data?.proposals.length===0&&<p className="mt-3 text-sm text-ink-dim">No accepted suggestions waiting to be applied.</p>}{data?.proposals.map(p=><div className="border-t border-hairline py-3 mt-3" key={p.id}><p>{p.topic}</p><p className="text-xs text-ink-dim">Accepted · not yet applied</p><button className="btn btn-secondary mt-2" disabled={busy} onClick={()=>inspect(p.id)}>Preview Notion update</button></div>)}{preview&&<div className="mt-4 border border-hairline p-3"><a href={preview.data.targetUrl} target="_blank" rel="noreferrer" className="underline">{preview.data.targetTitle} ↗</a><p className="my-3 whitespace-pre-wrap text-sm">{preview.data.text}</p><div className="flex gap-2"><button className="btn btn-primary" disabled={busy} onClick={apply}>Apply this amendment</button><button className="btn btn-secondary" disabled={busy} onClick={()=>setPreview(null)}>Cancel</button></div></div>}{history.data?.proposals?.length ? <details className="mt-5 border-t border-hairline pt-3"><summary className="cursor-pointer text-sm">Applied history ({history.data.proposals.length})</summary>{history.data.proposals.map(p=><div key={p.id} className="mt-3 text-sm"><p>{p.topic}</p>{p.appliedAt&&<time className="text-xs text-ink-dim">{new Date(p.appliedAt).toLocaleString()}</time>}{p.appliedUrl?.startsWith("https://www.notion.so/")&&<a className="ml-3 underline" href={p.appliedUrl} target="_blank" rel="noreferrer">View amended source ↗</a>}</div>)}</details>:null}</FrameCard>;
}
